<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>dc4e53bb-21a3-4f1d-ad36-3e43f8d2e5df</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\WhoopNet\WhoopNet.csproj" />
  </ItemGroup>

</Project>
